name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-windows-rdkit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: scifinder-env
          environment-file: environment.yml
          channels: conda-forge
          channel-priority: strict

      - name: Python info
        shell: bash
        run: |
          which python
          python --version
          conda list rdkit || true

      - name: Upgrade RDKit to latest
        shell: bash
        run: |
          conda install -y -c conda-forge rdkit

      - name: Install project (pip extras in env)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run tests
        shell: bash
        run: |
          pytest -q

  test-ubuntu-no-rdkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip deps (no RDKit)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q
